In [12]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parents[1]

meta_path = PROJECT_ROOT / "data" / "embeddings" / "cpt_meta.parquet"
print(meta_path, meta_path.exists())

df = pd.read_parquet(meta_path)
df.head()

/Users/laura/Documents/ml_projects/medical_cost_estimator/data/embeddings/cpt_meta.parquet True

,faiss_id,search_text,code,title,type,category
0,0,"""Anesthesia for Procedures on the Head.Anesthe...",100,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
1,1,"""Anesthesia for Procedures on the Head.Anesthe...",102,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
2,2,"""Anesthesia for Procedures on the Head.Anesthe...",103,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
3,3,"""Anesthesia for Procedures on the Head.Anesthe...",104,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
4,4,"""Anesthesia for Procedures on the Head.Anesthe...",120,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology

In [13]:
df = pd.read_parquet(PROJECT_ROOT / "data" / "embeddings" / "cpt_meta.parquet")
df.columns.tolist()

['faiss_id', 'search_text', 'code', 'title', 'type', 'category']

In [29]:
df2 = pd.read_csv(PROJECT_ROOT / "data" / "raw" / "cpt_hcpcs_hf.csv")
df2.columns.tolist()

['index', 'code', 'title', 'category', 'description', 'type']

In [18]:
medicine = df2[df2['category'] == 'Medicine']

In [19]:
medicine.head()

,index,code,title,category,description,type
0,0,100,"""Anesthesia for Procedures on the Head.Anesthe...",Medicine,"""The provider performs anesthesia services for...",CPT
1,1,102,"""Anesthesia for Procedures on the Head.Anesthe...",Medicine,"""The provider performs anesthesia services for...",CPT
2,2,103,"""Anesthesia for Procedures on the Head.Anesthe...",Medicine,"""The provider performs anesthesia services for...",CPT
3,3,104,"""Anesthesia for Procedures on the Head.Anesthe...",Medicine,"""The provider performs anesthesia services for...",CPT
4,4,120,"""Anesthesia for Procedures on the Head.Anesthe...",Medicine,"""The provider performs anesthesia services for...",CPT

In [21]:
medicine.info()

<class 'pandas.DataFrame'>
RangeIndex: 16056 entries, 0 to 16055
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        16056 non-null  int64
 1   code         16056 non-null  str
 2   title        16056 non-null  str
 3   category     16056 non-null  str
 4   description  16056 non-null  str
 5   type         16056 non-null  str
dtypes: int64(1), str(5)
memory usage: 4.8 MB

In [23]:
df2['category'].nunique()

1

In [31]:
eval = df2[df2['category'] == 'Evaluation and Management (E/M) Services']

In [32]:
eval.head()

,index,code,title,category,description,type
9501,9501,99201,"""New Patient.Physicians office. clinic or outp...",Evaluation and Management (E/M) Services,"""Office or other outpatient visit for the eval...",CPT
9502,9502,99202,"""New Patient.Physicians office. clinic or outp...",Evaluation and Management (E/M) Services,"""The provider sees a new patient for an office...",CPT
9503,9503,99203,"""New Patient.Physicians office. clinic or outp...",Evaluation and Management (E/M) Services,"""The provider sees a new patient for an office...",CPT
9504,9504,99204,"""New Patient.Physicians office. clinic or outp...",Evaluation and Management (E/M) Services,"""The provider sees a new patient for an office...",CPT
9505,9505,99205,"""New Patient.Physicians office. clinic or outp...",Evaluation and Management (E/M) Services,"""The provider sees a new patient for an office...",CPT